spring:
  application:
    name: mvc-service
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8090
